// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> prove({
  required String schemePath,
  required String inputPath,
  required String proofPath,
  required String tmpDirPath,
  required List<int> sod,
  required List<int> dg1,
}) => RustLib.instance.api.crateApiProve(
  schemePath: schemePath,
  inputPath: inputPath,
  proofPath: proofPath,
  tmpDirPath: tmpDirPath,
  sod: sod,
  dg1: dg1,
);
